---
title: "Australia"
author: "Stephanie Kobakian"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library(purrr)
library(sf)
library(viridis)
library(ggthemes)
library(plotly)
library(geofacet)
```


The sugaRbag package can be downloaded directly from github:

```{r}
#devtools::install_github("srkobakian/sugaRbag")
library(sugaRbag)
```

It also contains the location of the Australian capital cities and information about the upper heirarchy levels the SA2 areas belong to.

```{r}
load(system.file("data","sa2_2011.Rda", package = "sugaRbag"))
load(system.file("data","capital_cities.Rda", package = "sugaRbag"))

```



```{r map1}
aus_sfc <- sf::st_as_sf(shp)
```

```{r, eval = FALSE}
hexmap <- create_hexmap(shp = aus_sfc,
    sf_id = "NAME",
    hex_size = 0.3,
    buffer_dist = 6,
    filter_dist = 2,
    export_shp = FALSE,
    focal_points = capital_cities, verbose = TRUE)
```


```{r, echo = FALSE}
load(system.file("data","hexmap_aus_3.Rda", package = "sugaRbag"))
```

The hexagon locations for each area polygon are returned.

```{r}
# converting to fortified tibble
fortified_aus_3 <- fortify_sfc(aus_sfc)

# join to geometry data
hexmap_aus_3 <- left_join(hexmap_aus_3, fortified_aus_3, by = c("SA2_NAME11"))
```


```{r}

# Full aus map
ggplot(data=hexmap_aus_3 %>% filter(GCC_NAME11=="Greater Perth")) +
    geom_hex(aes(x = hex_long, y = hex_lat, fill=STE_NAME11), position = "identity", stat = "identity") +
    geom_polygon(aes(x=long,y=lat,group=group), colour = "grey", fill = NA) +
    scale_fill_viridis_d() +
    guides(fill = FALSE) +
    theme(aspect.ratio = 1)

```


```{r, fig.height=12, fig.width=6}
# Facet by STE
#load("data/aus_grid.rda")
ggplot(aus_sfc) +
    geom_sf(aes(fill = STE_NAME11, label = SA2_NAME11)) +
    scale_fill_viridis_d() +
    guides(fill = FALSE)


ggplot(data=hexmap_aus_3) +
    geom_hex(aes(x = hex_long, y = hex_lat, fill=STE_NAME11,
        label = SA2_NAME11), position = "identity", stat = "identity") +
    geom_polygon(aes(x=long,y=lat,order=order,group=group), colour = "grey", fill = NA) +
    scale_fill_viridis_d() +
    facet_geo(~STE_NAME11, scales = "free", grid = aus_grid1) +
    guides(fill = FALSE) +
    theme(strip.text.x = element_text(size = 5),
        strip.background = element_rect(fill = NA, size = 1),
        axis.text = element_blank(),
        aspect.ratio = 1)
```


