---
title: "Local Government Areas"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
    fig.height = 5, fig.width = 8)
```

Local Government Areas of Australia in 2011.

```{r}
library(sugaRbag)
library(dplyr)
library(ggplot2)
library(purrr)

load(system.file("data","lga_2011.Rda", package = "sugaRbag"))
load(system.file("data","capital_cities.Rda", package = "sugaRbag"))
```

Only consider Victoria

```{r}
vic_lga <- lga_2011 %>% filter(STE_NAME11 == "Victoria")

```

Create the map

```{r}
hexmap_vic_lga <- create_hexmap(shp = vic_lga, sf_id = "LGA_NAME11", buffer_dist = NULL,
filter_dist = 4, hex_size = NULL, export_shp = FALSE,
focal_points = capital_cities[1,], verbose = TRUE, width = 20)
```


```{r}
ggplot(data = hexmap_vic_lga) +
    geom_hex(aes(x = hex_long, y = hex_lat), position = "identity", stat = "identity") + coord_fixed()
```


```{r}
ggplot(data = hexmap_vic_lga) +
    geom_segment(aes(x = longitude, xend = hex_long, y = latitude, yend = hex_lat), arrow = arrow(length = unit(0.1,"cm"))) + coord_fixed()
```

```{r}
fortified_lga <- fortify_sfc(vic_lga)

ggplot() +
    geom_segment(data = hexmap_vic_lga, mapping = aes(x = longitude, xend = hex_long, y = latitude, yend = hex_lat, label = LGA_NAME11), arrow = arrow(length = unit(0.1,"cm"))) +
    geom_polygon(data = fortified_lga, mapping = aes(x = long, y = lat, group = group), fill=NA, colour ="grey") + coord_fixed()
```


# Impact of angle around direction

```{r, eval = FALSE}
angles <- seq(5, 65, 10)

hexmap_vic_lga_set <- angles %>%
    map( ~
            {  angle_width = .
            
                a <- create_hexmap(shp = vic_lga, sf_id = "LGA_NAME11", buffer_dist = 2,
filter_dist = 4, hex_size = 0.2, export_shp = FALSE,
focal_points = capital_cities[1,], verbose = TRUE, width = angle_width) %>% mutate(angle_width = angle_width) %>%
                    rowwise %>%
            mutate(dist = geosphere::distVincentyEllipsoid(
        c(longitude, latitude), 
        c(hex_long, hex_lat),
        a=6378160, b=6356774.719, f=1/298.257222101)) 
        }
        ) 

sumdist <- hexmap_vic_lga_set %>%
    map_dfr(.f = function(x){ x %>% ungroup %>%
                    summarise(angle = mean(angle_width), sum = sum(dist))
    }) %>%
    arrange(sum)

plots <- hexmap_vic_lga_set %>%
    map(.f = function(x){ 
        tangle <- x$angle_width[1]
        tsum <- sum(x$dist)
        #arrow plots of distance moved using geom_segment
        ggplot(x) +
            geom_segment(aes(x=longitude, xend = hex_long, y = latitude, yend= hex_lat), arrow = arrow(length = unit(0.2, "cm"))) + coord_fixed() + labs(subtitle = paste0("Filter Angle: ", tangle,", sum of distances: ", round(tsum/1000, 1), " kms"))
    })

```


```{r}
library(gridExtra)
nCol <- floor(sqrt(length(plots)))
do.call("grid.arrange", c(plots, ncol=nCol))
```

