---
title: "Queensland"
author: "Stephanie Kobakian"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(sugaRbag)
library(ggplot2)
library(dplyr)
library(sf)
library(viridis)
library(geofacet)
```


# Queensland

```{r map1}
load(system.file("data","lga_2011.Rda", package = "sugaRbag"))
load(system.file("data","capital_cities.Rda", package = "sugaRbag"))

shp_sfc <- sf::st_as_sf(lga_2011)
qld_sfc <- shp_sfc %>% dplyr::filter(STE_NAME11=="Queensland")

qld_sfc$LGA_CODE11 <-
droplevels(qld_sfc$LGA_CODE11)
```

```{r}
hexmap_qld_3 <- create_hexmap(shp = qld_sfc,
    sf_id = "LGA_CODE11",
    hex_size = 0.3,
    export_shp = FALSE,
    focal_points = capital_cities[5,], verbose = TRUE)
```

```{r}
# join to geometry data
hexmap_qld_3 <- left_join(hexmap_qld_3, qld_sfc,
    by = c("LGA_CODE11"))

# converting to fortified tibble
fortified_qld_3 <- fortify_sfc(hexmap_qld_3)
```



```{r}
load(system.file("data","qld_grid.Rda", package = "sugaRbag"))

ggplot(qld_sfc) +
    geom_sf(aes(label = LGA_CODE11)) +
    scale_fill_viridis_d() +
    guides(fill = FALSE)


ggplot(data=fortified_qld_3) +
    geom_hex(aes(x = hex_long, y = hex_lat,
        label = LGA_CODE11), position = "identity", stat = "identity") +
    geom_polygon(aes(x=long,y=lat,order=order,group=group), colour = "grey", fill = NA) +
    scale_fill_viridis_d() +
    guides(fill = FALSE) +
    theme(strip.text.x = element_text(size = 5),
        strip.background = element_rect(fill = NA, size = 1),
        axis.text = element_blank(),
        aspect.ratio = 1)

```


```{r}

# Full Qld map
ggplot(data=fortified_qld_3) +
    geom_hex(aes(x = hex_long, y = hex_lat,
        label = LGA_CODE11), position = "identity", stat = "identity") +
    geom_polygon(aes(x=long,y=lat,order=order,group=group), colour = "grey", fill = NA) +
    scale_fill_viridis_d() +
    guides(fill = FALSE) +
    theme(aspect.ratio = 1)

```


