---
title: "Spatial Distributions"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}

#library(sugaRbag)

library(tidyverse)
#library(purrr)
library(sf)
library(viridis)
library(ggthemes)
library(geofacet)
```


```{r}
load(system.file("data","sa2_2011.Rda", package = "sugaRbag"))
load(system.file("data","capital_cities.Rda", package = "sugaRbag"))
load(system.file("data","fortified_aus_3.Rda", package = "sugaRbag"))
load(system.file("data","SIR_Downloadable_Data.Rda", package = "sugaRbag"))

aus_mel <- SIR_Downloadable_Data %>%
    filter(Cancer_name=="Lung") %>%
    filter(Sex_name == "Persons")

shp_sfc <- sf::st_as_sf(shp)

```

```{r, eval = FALSE}
hexmap <- create_hexmap(shp = shp_sfc,
    sf_id = "SA2_NAME11",
    hex_size = 0.3,
    export_shp = FALSE,
    focal_points = capital_cities, verbose = TRUE)
```

```{r, echo = FALSE}
load(system.file("data","hexmap_aus_3.Rda", package = "sugaRbag"))
```


```{r}
aus_mel <- SIR_Downloadable_Data %>%
    filter(Cancer_name== "Melanoma") %>%
    filter(Sex_name == "Persons") %>%
    filter(SA2_name %in% fortified_aus_3$SA2_NAME11)

fortified_SIR <- left_join(fortified_aus_3, aus_mel, by = c("SA2_NAME11"="SA2_name"))

ggplot(data=fortified_SIR) +
    geom_hex(aes(x = hex_long, y = hex_lat, fill = p50), position = "identity", stat = "identity") +
    scale_fill_viridis() +
    guides(fill = FALSE) +
    theme(aspect.ratio = 1)
```

```{r}
ggplot(data=fortified_SIR) +
    scale_fill_viridis_c() +
    #guides(fill = FALSE) +
    theme(aspect.ratio = 1) +
    geom_polygon(aes(x=long,y=lat,group=group, fill = p50))
    
```


```{r}
aus_mel <- SIR_Downloadable_Data %>%
    filter(Cancer_name=="Melanoma") %>%
    filter(Sex_name == "Persons") %>%
    filter(SA2_name %in% fortified_aus_3$SA2_NAME11)

fortified_mel <- left_join(fortified_aus_3, aus_mel, by = c("SA2_NAME11"="SA2_name"))

```


```{r}
ggplot(data=fortified_mel) +
    geom_hex(aes(x = hex_long, y = hex_lat, fill = p50), position = "identity", stat = "identity") +
    scale_fill_viridis() +
    guides(fill = FALSE) +
    theme(aspect.ratio = 1)
```

```{r}
ggplot(data=fortified_mel) +
    scale_fill_viridis_c() +
    #guides(fill = FALSE) +
    theme(aspect.ratio = 1) +
    geom_polygon(aes(x=long,y=lat,group=group, fill = p50))
    
```

